# Generated by Django 4.2.7 on 2023-12-08 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcategorymodel',
            old_name='task_model_relation',
            new_name='TaskModel',
        ),
    ]
