# Generated by Django 4.2.7 on 2023-12-08 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_task_model_relation_taskcategorymodel_taskmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcategorymodel',
            old_name='TaskModel',
            new_name='taskModel',
        ),
    ]
