# Generated by Django 4.2.7 on 2023-12-08 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_rename_taskmodel_taskcategorymodel_taskmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcategorymodel',
            old_name='taskModel',
            new_name='TaskModel',
        ),
    ]
