# Generated by Django 4.2.7 on 2023-12-08 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_taskmodel_taskcategorymodel_taskmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcategorymodel',
            name='TaskModel',
        ),
    ]
