# Generated by Django 4.2.7 on 2023-12-08 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskmodel_category_alter_taskmodel_task_assign_date'),
        ('category', '0005_remove_taskcategorymodel_taskmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskCategoryModel',
            new_name='Category',
        ),
    ]
