# Generated by Django 4.2.7 on 2023-12-08 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskmodel_category_alter_taskmodel_task_assign_date'),
        ('category', '0006_rename_taskcategorymodel_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='TaskCategoryModel',
        ),
    ]
